version: "3.3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "flask db init && flask db migrate -m 'First migration' && flask db upgrade && python3 app.py"
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://chou:calamardo@db:5432/postgres
    expose:
      - 8000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: chou
      POSTGRES_PASSWORD: calamardo
    volumes:
      - .dbdata:/var/lib/postgresql/data
    ports:
      - 55432:5432